services:
  - type: web
    name: mira-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false
